    # Copyright 2013-2015 Iron Summit Media Strategies, LLC

    # Licensed under the Apache License, Version 2.0 (the "License");
    # you may not use this file except in compliance with the License.
    # You may obtain a copy of the License at

    #     http://www.apache.org/licenses/LICENSE-2.0

    # Unless required by applicable law or agreed to in writing, software
    # distributed under the License is distributed on an "AS IS" BASIS,
    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    # See the License for the specific language governing permissions and
    # limitations under the License.
   
    # Notice: This file has been modified from its original form by Tom Van Manen, 2020
    # See https://github.com/volny/creative-theme-jekyll for original files.
#
#
# 
#
# Site settings
title: stir it up
author: Natalie Justin
email: stiritupfoods@yahoo.com
phone: +1-778-432-0133
facebook_url: https://www.facebook.com/Stir-it-Up-133468816703389/
description: > # this means to ignore newlines until "baseurl:"
  Stir it up is a locally owned Authentic Caribbean Soul Food restaurant. Originally from St. Lucia, Chef/Owner Natalie Justin's menu features fresh ingredients, amazing spices and exotic influences.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ciraben.github.io/stiritup/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: [stiritup/]
